# rule identifiers to exclude from running
disabled_rules:
  - empty_parameters
  - identifier_name
  - file_length
  - empty_parentheses_with_trailing_closure
  - colon
  - force_cast
  - cyclomatic_complexity
  - line_length
  - class_delegate_protocol
  - nesting
  - implicit_getter
  - for_where
  - notification_center_detachment
  - comma
  - compiler_protocol_init
  - force_try
  - function_parameter_count
  - trailing_whitespace  
  - opening_brace

# rule identifiers to opt in
opt_in_rules:
  - closure_end_indentation
  - fatal_error_message
  - closure_spacing

# special configuration for rules 
large_tuple:
  warning: 2
  error: 3

function_body_length:
  warning: 40
  error: 100

# paths to include during linting.
included:
  - Sources

excluded:
  - Sources/SwiftRules/Wrong.swift

custom_rules:
  
  invalid_open_brace:
    name: "Invalid Open Brace"
    regex: '[a-zA-Z)] ?\{$'
    message: "Open brace should start on its own line"
    severity: error
